# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths: 
    include:
      - api/aws_lambda/

pool:
  vmImage: 'ubuntu-latest'

variables:
  ZIP_FILENAME: FivetranFunctionLambda

steps:
- script: cd api/aws_lambda/ && npm i
  displayName: NPM Install
  
- task: ArchiveFiles@2
  displayName: Zip Files
  inputs:
    rootFolderOrFile: './api/aws_lambda/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(ZIP_FILENAME).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
